apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJjekY2Wlc1c2VUcG5hSEJmU2tkWVdHczNVVVF5YWpSd1RYSmtia2xNUzBoVWNGQTRWVEZDWjBZNE1FWXhja2cyIgoJCX0KCX0sCgkiY3VycmVudENvbnRleHQiOiAiY29saW1hIgp9
type: kubernetes.io/dockerconfigjson
